# -*- coding: utf-8 -*-
"""IceCreamSales.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DvVova_8zS-pABG1WmxnWjKHC3C6Jzbo
"""

import csv
import plotly.express as px


with open("./iceCream.csv",encoding="utf-8") as csv_file:
    df = csv.DictReader(csv_file)
    fig = px.scatter(df,x = 'Temperature',y = 'Ice-cream Sales( ₹ )' )
    fig.show()